apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primerjalnik-cen
  template:
    metadata:
      labels:
        app: primerjalnik-cen
    spec:
      containers:
        - image: edelwy/primerjalnik-cen
          name: primerjalnik-cen
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/zqjqqtrd
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: zqjqqtrd
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: <geslo>
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: primerjalnik-cen
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: primerjalnik-cen