kumuluzee:
  name: primerjalnik_cen
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://172.17.0.2:5432/primerjalnik-cen
      username: postgres
      password: postgres

