kumuluzee:
  name: primerjalnik_cen
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://mel.db.elephantsql.com:5432/mmirewmm
      username: mmirewmm
      password: UxkXJHPPZjMBVQJWRmT8hAtoSdXzfdr_

